### POST Login users
POST http://localhost:8080/api/auth/login

### POST users
POST http://localhost:8080/api/users
#Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "123456",
  "username": "test01"
}

### DELETE users
DELETE http://localhost:8080/api/users/1
#Authorization: Bearer {{auth_token}}

###