### Find all customers
GET http://localhost:8080/api/customers

### Find customer by id
GET http://localhost:8080/api/customers/1

### Create customer
POST http://localhost:8080/api/customers
Content-Type: application/json

{
  "firstName": "Marco",
  "lastName": "Le"
}

### Update customer
PUT http://localhost:8080/api/customers/1
Content-Type: application/json

{
  "firstName": "Anh",
  "lastName": "Vu"
}

### Delete customer
DELETE http://localhost:8080/api/customers/2
